### ISSUE TITLE
Fail to start using node from snap package

### ISSUE THREAD

**Issue by jyte** [romgrk/node-gtk#116]
Hi,
I tried to run the example using node installed from the snap store on ubuntu but it fails with the following error :

```
$ node index.js 

** (process:26467): WARNING **: Failed to load shared library 'libcairo-gobject.so.2' referenced by the typelib: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)

** (process:26467): WARNING **: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
**
ERROR:../src/gobject.cc:349:Local<v8::FunctionTemplate> GNodeJS::NewClassTemplate(GIBaseInfo *, GType): assertion failed: (gtype != G_TYPE_NONE)
Abandon (core dumped)
```

It works fine when using node installed from ubuntu repository

**Comment by WebReflection** [comment]
that's the curse of snap'd and flatpak'd packages, you either pre bundle a new snap with all dependencies known upfront included, or you'll be likely out of luck.

If node there is not packaged with all Gtk related dependencies you need, you'll have hard time.

However, if you want to create a snap with node and gtk already available, you can do that, and see this project working without issues.

**Comment by romgrk** [comment]
Indeed, the problem here is that the required dependencies are not installed, which is not directly an issue of node-gtk. I'm closing as it's not actionnable for the next year at least, but if someone is really interested in creating a node + Gtk snap, please re-open.

**Comment by kevindurb** [comment]
I am really interested in creating a node + Gtk snap :) Im actually working on creating my first snap! I have a working typescript + node-gtk app that runs on ubuntu 20.04. Im actually getting a build error when i run `snapcraft`
```
> node-gtk@0.4.0 install /root/parts/ts-gtk/install/lib/node_modules/jsgtk/node_modules/node-gtk
> if [ "$(uname)" = "Darwin" ] && [ "$(which brew)" != "" ]; then export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig; fi; node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! node-gtk@0.4.0 install: `if [ "$(uname)" = "Darwin" ] && [ "$(which brew)" != "" ]; then export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig; fi; node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-gtk@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-26T21_28_08_150Z-debug.log
Failed to build 'ts-gtk'.

Recommended resolution:
Check the build logs and ensure the part's configuration and sources are correct.
```

heres my snapcraft.yaml
```
name: ts-gtk
version: '1.0'
summary: A Typescript GTK Starter Template
description: Opens a basic gtk app

confinement: devmode
base: core20

parts:
  ts-gtk:
    plugin: npm
    source: https://github.com/kevindurb/ts-gtk.git
    npm-node-version: 14.2.0
    build-packages:
      - build-essential
      - git
      - gobject-introspection
      - libgirepository1.0-dev
      - libcairo2
      - libcairo2-dev

apps:
  ts-gtk:
    command: npm start
```
